server:
  port: 8088
  #  context-path: /mydemo

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.xuhu.demo.domain
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
